name: agent-edge-rknn

services:
  # -- YOLOv8 NPU INFERENCE NODE --
  yolov8-npu:
    image: ghcr.io/bob-ros2/bob-edge-rknn:latest
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.rknn
      args:
        BASE_IMAGE: ghcr.io/bob-ros2/bob-edge:latest
    container_name: agent-yolo-npu
    ports:
      - "8080:8080"  # HTTP Port for MJPEG Stream
    networks:
      - agent-net
    dns:
      - 192.168.32.100
      - 8.8.8.8
    env_file:
      - ../.env
      - /volume1/ros/secrets/edge_agent.env
    environment:
      - AGENT_ID=${AGENT_ID:-main_agent}
      - CAMERA_INDEX=${CAMERA_INDEX:-1}
    devices:
      - /dev/rknpu:/dev/rknpu      # Expose NPU
    privileged: true               # Needed for direct NPU and USB hardware access
    restart: on-failure
    volumes:
      - ../:/ros2_ws/src/bob_edge:ro
      - /volume1/ros/agent:/home/rosuser/agent
      - /volume1/ros/agent/tmp:/tmp
      - /dev:/dev                  # Mount entire /dev to support USB camera hot-plugging
    command: ros2 run bob_edge yolov8_npu

networks:
  agent-net:
    external: true
