[develop]
script_dir=$base/lib/bob_edge
[install]
install_scripts=$base/lib/bob_edge
[options.entry_points]
console_scripts =
    orchestrator = bob_edge.orchestrator_node:main
    repl = bob_edge.repl_node:main
    ws_dashboard = bob_edge.ws_dashboard_node:main
    yolov8_npu = bob_edge.yolov8_npu_node:main
