name: ROS 2 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ros:humble
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          . /opt/ros/humble/setup.sh
          mkdir -p ros2_ws/src
          ln -s ../.. ros2_ws/src/bob_edge
          cd ros2_ws
          colcon build --packages-select bob_edge
      - name: Test
        run: |
          . /opt/ros/humble/setup.sh
          cd ros2_ws
          colcon test --packages-select bob_edge
